# Generated by Django 2.2.6 on 2019-10-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contest',
            fields=[
                ('C_id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=200, unique=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('duration', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
