# Generated by Django 2.2.6 on 2019-10-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='event',
            field=models.CharField(max_length=200),
        ),
    ]
