# Generated by Django 2.2.6 on 2019-10-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIServer', '0002_auto_20191010_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='domain',
            field=models.URLField(default='www.codechef.com'),
        ),
        migrations.AddField(
            model_name='contest',
            name='href',
            field=models.URLField(default='www.codechef.com'),
        ),
    ]
