# Generated by Django 2.2.6 on 2019-10-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
